Add collector for ssacli
canonical/prometheus-hardware-exporter pull request #12
Opened 2023-06-21 02:41 UTC by sudeephb

2023-06-21 04:45 UTC, Pjack requested changes

2023-06-21 04:45 UTC, Pjack commented on prometheus_hardware_exporter/collector.py
> +                metric_class=GaugeMetricFamily,
Please use InfoMetricFamily and the naming could be ssacli_controller_info
Sample code: https://github.com/canonical/prometheus-hardware-exporter/blob/main/prometheus_hardware_exporter/collector.py#LL52C30-L52C46

2023-06-21 04:45 UTC, Pjack commented on prometheus_hardware_exporter/collector.py
> +                metric_class=GaugeMetricFamily,
Please use InfoMetricFamily and the naming could be ssacli_ld_info

2023-06-21 04:45 UTC, Pjack commented on prometheus_hardware_exporter/collector.py
> +                metric_class=GaugeMetricFamily,
Please use InfoMetricFamily and the naming could be ssacli_pd_info

2023-06-21 04:45 UTC, Pjack commented on prometheus_hardware_exporter/collector.py
> +                        value=self._get_status_value(status),
The design seems different than other collectors. 
https://github.com/canonical/prometheus-hardware-exporter/blob/main/prometheus_hardware_exporter/collector.py#L143

Do we want to align the design ?

Solution 1: state as an info in label
Solution 2: status as a value , 1: healthy, 0: unhealthy

2023-06-26 08:10 UTC, Pjack approved these changes
LGTM

2023-06-26 09:39 UTC, Pjack commented on prometheus_hardware_exporter/collector.py
> +                name="ssacli_ld",
+1

2023-06-27 02:39 UTC, jneo8 approved these changes

2023-06-27 05:24 UTC, merged