refactor: Use parameterized in redfish unit tests.
canonical/prometheus-hardware-exporter pull request #55
Opened 2023-12-04 17:21 UTC by dashmage

Use the [parameterized](https://pypi.org/project/parameterized/) package in the `test_redfish.py` unit tests. This allows us to more easily create similar looking tests which only differ in the parameters being passed to them.

Resolves #53

2023-12-05 01:26 UTC, Pjack requested changes
Thanks! It's a good refactor. And after the refactor, I also realize we miss some test case for the fail case. Could you help to add them? thanks!
get_storage_drive_data_fail
get_storage_controller_data_fail

2023-12-05 05:30 UTC, dashmage commented
> Thanks! It's a good refactor. And after the refactor, I also realize we miss some test case for the fail case. Could you help to add them? thanks! get_storage_drive_data_fail get_storage_controller_data_fail

Sure thing, good suggestion. Although in this PR, I'd like to contain the scope and not add any new tests, just refactor existing ones to make it more cleaner using the `parameterized` package.

I'll create a new issue and will add the tests as part of that one :)

2023-12-05 06:07 UTC, Pjack approved these changes

2023-12-05 08:34 UTC, rgildein approved these changes
I like the usage of parametrize, and this changes are LGTM to me.

2023-12-05 08:34 UTC, rgildein commented on tests/unit/test_redfish.py
>              elif "Systems" in uri:
I do not see how this is used.

2023-12-06 08:41 UTC, rgildein commented on tests/unit/test_redfish.py
>              elif "Systems" in uri:
This clarify it thank , I assumed that was there by design. Thanks

2023-12-06 08:55 UTC, merged